# Generated by Django 2.0.2 on 2018-03-20 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_auto_20180320_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='contact_num',
        ),
    ]
